#!/bin/bash

HOST="arch"
LOCALE="America/Sao_Paulo"
KEYBOARD="br-abnt2"
LANGUAGE="pt_BR"
ROOTPASS="root"
USERNAME="archer"
USERPASS="666"
SWAPSIZE="512"

DISK="/dev/sda"
SERVER="Brazil"

loadkeys $KEYBOARD && fdisk -l && parted -s $DISK mklabel gpt && parted -s $DISK mkpart primary fat32 1M 129M && parted -s $DISK set 1 esp on && parted -s $DISK set 1 boot on && parted -s $DISK mkpart primary ext4 129M 100% && echo -e "\n\n\nParticionamento concluído!\n\n\n" && fdisk -l && mkfs.vfat -F32 -n "ESP" $DISK'1'  && mkfs.ext4 -L "ARCH" $DISK'2' && mount $DISK'2' /mnt && mkdir -p /mnt/{boot/efi,home} && mount $DISK'1' /mnt/boot/efi && echo -e "\n\n\nMontagem concluída!\n\n\n" && dd if=/dev/zero of=/mnt/swapfile bs=1024K count=$SWAPSIZE conv=noerror,sync status=progress && chmod 600 /mnt/swapfile && mkswap /mnt/swapfile && swapon /mnt/swapfile && echo -e "\n\n\nSwapfile criado e montado!\n\n\n" && lsblk -o name,mountpoint,label,size,fstype,uuid && cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak && sed "s/^Ser/#Ser/" /etc/pacman.d/mirrorlist > /tmp/mirrors && sed "/$SERVER/{n;s/^#//}" /tmp/mirrors > /etc/pacman.d/mirrorlist && nano /etc/pacman.d/mirrorlist && pacstrap /mnt base base-devel linux linux-firmware nano networkmanager && genfstab -U /mnt >> /mnt/etc/fstab && echo -e "\n\n\nSistema base instalado!\n\n\n" && arch-chroot /mnt << EOF 
echo $HOST > /etc/hostname && cp /etc/hosts /etc/hosts.bak && echo -e "\n127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t$HOST.localdomain\t$HOST" >> /etc/hosts && cat /etc/hosts && echo 'KEYMAP='$KEYBOARD > /etc/vconsole.conf && cp /etc/locale.gen /etc/locale.gen.bak && sed 's/^#'$LANGUAGE'/'$LANGUAGE/ /etc/locale.gen > /tmp/locale && mv /tmp/locale /etc/locale.gen && locale-gen && echo 'LANG='$LANGUAGE'.UTF-8' > /etc/locale.conf && export LANG=$LANGUAGE'.UTF-8' && export KEYMAP=$LANGUAGE'.UTF-8' && ln -sf /usr/share/zoneinfo/$LOCALE /etc/localtime && hwclock -w -u && cp /etc/pacman.conf /etc/pacman.conf.bak && sed '/^#\[multilib\]/{s/^#//;n;s/^#//;n;s/^#//}' /etc/pacman.conf > /tmp/pacman && mv /tmp/pacman /etc/pacman.conf && pacman -Syy --noconfirm bash-completion networkmanager ntfs-3g grub-efi-x86_64 efibootmgr os-prober intel-ucode && mkinitcpio -P && grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch --recheck && grub-mkconfig -o /boot/grub/grub.cfg && echo -e $ROOTPASS"\n"$ROOTPASS | passwd && useradd -m -s /bin/bash -g users -G wheel,lp,video,audio,optical,storage,scanner,power,rfkill,adm,dbus,mail,tty,ftp,http,log,sys,disk,input $USERNAME && echo -e $USERPASS"\n"$USERPASS | passwd $USERNAME && echo "vm.swappiness=20" > /etc/sysctl.d/99-swappiness.conf && echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf && echo -e "\n\n\nConfiguração concluída!\n\n\n" && pacman -S --noconfirm xorg-{server,xinit,xkill,xinput,xrandr,xbacklight} mesa mesa-libgl libvdpau-va-gl lib32-mesa-libgl lib32-mesa-vdpau vulkan-radeon mesa-vdpau xbindkeys xdg-{utils,user-dirs} xf86-{video-{intel,amdgpu},input-{mouse,keyboard,synaptics}} pulseaudio pulseaudio-alsa pavucontrol alsa-{utils,firmware,plugins} ntfs-3g dosfstools exfat-utils f2fs-tools fuseiso libgphoto2 gphoto2 fuse-exfat autofs mtpfs libmtp android-udev gvfs-{mtp,gphoto2,afc,smb} tlp acpi acpid bluez bluez-utils xterm && pacman -S --noconfirm awesome vicious hddtemp wireless_tools firefox-i18n-pt-br ttf-roboto lightdm-gtk-greeter network-manager-applet && systemctl enable lightdm.service && systemctl enable NetworkManager.service && echo -e "Section \"InputClass\"\n\tIdentifier \"touchpad catchall\"\n\tDriver \"synaptics\"\n\tMatchIsTouchpad \"on\"\n\tMatchDevicePath \"/dev/input/event*\"\n\tOption \"TapButton1\" \"1\"\n\tOption \"TapButton2\" \"2\"\n\tOption \"TapButton3\" \"3\"\n\tOption \"VertTwoFingerScroll\" \"1\"\n\tOption \"HorizTwoFingerScroll\" \"1\"\n\tOption \"VertScrollDelta\" \"-30\"\n\tOption \"HorizScrollDelta\" \"-30\"\n\tOption \"LockedDrags\" \"1\"\n\tOption \"LockedDragTimeout\" \"1000\"\nEndSection\n" > /usr/share/X11/xorg.conf.d/70-synaptics.conf && echo -e "Section \"OutputClass\"\n\tIdentifier \"Intel Graphics\"\n\tDriver \"intel\"\n\tOption \"AccelMethod\" \"sna\"\n\tOption \"TearFree\" \"True\"\n\tOption \"Tiling\" \"True\"\n\tOption \"SwapbuffersWait\" \"True\"\nEndSection" > /usr/share/X11/xorg.conf.d/20-intel.conf && echo "end..."
EOF

echo -e "\n\n\nConcluído\n\n\n"

